version: '3.8'

services:
  app:
    build: .
    container_name: parking_system_container  
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    
    environment:
    - SECRET_KEY=${SECRET_KEY}
    - ALGORITHM=${ALGORITHM}
    - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    - SMTP_SERVER=${SMTP_SERVER}
    - SMTP_PORT=${SMTP_PORT}
    - SMTP_USER=${SMTP_USER}
    - SMTP_PASSWORD=${SMTP_PASSWORD}
    - BACKEND_PORT=${BACKEND_PORT}
    - DATABASE_URL=${DATABASE_URL}

    depends_on:
      - postgres
    networks:
      - backend_network

  postgres:
    image: postgres:latest
    container_name: pg_pk_sys_db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
